In [15]:
#-----------------pytorch中的主要函数------------------
#抽样函数
import torch
torch.seed()#生成一个64位随机数
torch.manual_seed(42)#设置生成随机数的种子并返回一个torch.generator对象
torch.initial_seed()#返回生成随机数的原始种子值
torch.get_rng_state()#生成一个随机生成器状态
rng_state1 = torch.get_rng_state()
print(rng_state1)
torch.set_rng_state(rng_state1*2)#设定随机生成器的状态
rng_state2 = torch.get_rng_state()
print(rng_state2)

tensor([42,  0,  0,  ...,  0,  0,  0], dtype=torch.uint8)
tensor([84,  0,  0,  ...,  0,  0,  0], dtype=torch.uint8)


In [3]:
pip install tqdm

In [5]:
import torch

# 创建需要梯度的叶子节点
x = torch.tensor([2.0], requires_grad=True)
y = torch.tensor([3.0], requires_grad=True)

# 前向计算
z = x * y
loss = z ** 2

# 方法1：使用 loss.backward(retain_graph=True)
loss.backward(retain_graph=True)  # 保留计算图
print(f"第一次反向传播后:")
print(f"x.grad: {x.grad}")  # 36
print(f"y.grad: {y.grad}")  # 24

# 手动清零梯度（注意：只是清零梯度值，计算图还在）
x.grad = None
y.grad = None

# 方法2：再次反向传播（现在可以了）
torch.autograd.backward(loss)
print(f"\n第二次反向传播后:")
print(f"x.grad: {x.grad}")  # 再次计算得到 36
print(f"y.grad: {y.grad}")  # 再次计算得到 24

第一次反向传播后:
x.grad: tensor([36.])
y.grad: tensor([24.])

第二次反向传播后:
x.grad: tensor([36.])
y.grad: tensor([24.])


In [7]:
#torch.autograd.grad()
import torch
x = torch.tensor([3.],requires_grad = True)
y = torch.pow(x,2)
grad1 = torch.autograd.grad(y,x,create_graph = True)
print(grad1)
grad2 = torch.autograd.grad(grad1[0],x)
print(grad2)

(tensor([6.], grad_fn=<MulBackward0>),)
(tensor([2.]),)


In [9]:
#---------------pytorch统计函数-----------------
import torch
a = torch.tensor([1.0,2.0,3.0,4.0])
print(torch.prod(a))#乘积

tensor(24.)


In [18]:
#求和
import torch
a = torch.rand(2,2)#随机生成一个2*2矩阵
print(a)
a1 = torch.sum(a)
a2 = torch.sum(a,dim = (0,1))#dim等于0队列求和 等于1对行求和
a3 = torch.sum(a,dim = 1,keepdim = True)#keepdim保留结果的维度
a4 = torch.sum(a,dim = 0,keepdim = True)
print(a1,a2,a3,a4)

tensor([[0.0041, 0.6808],
        [0.0089, 0.4917]])
tensor(1.1856) tensor(1.1856) tensor([[0.6850],
        [0.5006]]) tensor([[0.0131, 1.1725]])


In [23]:
#平均值
a = torch.rand(2,2)
a1 = torch.mean(a)
a2 = torch.mean(a,dim = 1,keepdim = True)
a3 = torch.mean(a,dim = 0,keepdim = True)
a4 = torch.mean(a,dim = (0,1))
print(a)
print(a1)
print(a2)
print(a3)
print(a4)


tensor([[0.8352, 0.1854],
        [0.6379, 0.6145]])
tensor(0.5683)
tensor([[0.5103],
        [0.6262]])
tensor([[0.7366, 0.4000]])
tensor(0.5683)


In [27]:
#最大值
a = torch.rand(2,2)
a1 = torch.max(a)
a2 = torch.max(a,dim = 1,keepdim = True)
a3 = torch.max(a,dim = 0,keepdim = True)
print(a)
print(a1)
print(a2)
print(a3)
#最小值同理 用torch.min函数

tensor([[0.1453, 0.7352],
        [0.1456, 0.0760]])
tensor(0.7352)
torch.return_types.max(
values=tensor([[0.7352],
        [0.1456]]),
indices=tensor([[1],
        [0]]))
torch.return_types.max(
values=tensor([[0.1456, 0.7352]]),
indices=tensor([[1, 0]]))


In [28]:
#中位数
a = torch.rand(3,3)
a1 = torch.median(a)
a2 = torch.median(a,dim = 1,keepdim = True)
a3 = torch.median(a,dim = 0,keepdim = True)
print(a)
print(a1)
print(a2)
print(a3)

tensor([[0.3048, 0.7487, 0.0872],
        [0.9910, 0.3536, 0.8608],
        [0.8386, 0.0283, 0.6782]])
tensor(0.6782)
torch.return_types.median(
values=tensor([[0.3048],
        [0.8608],
        [0.6782]]),
indices=tensor([[0],
        [2],
        [2]]))
torch.return_types.median(
values=tensor([[0.8386, 0.3536, 0.6782]]),
indices=tensor([[2, 1, 2]]))


In [29]:
#众数
a = torch.rand(10,10)
a1 = torch.mode(a)
a2 = torch.mode(a,dim = 1,keepdim = True)
a3 = torch.mode(a,dim = 0,keepdim = True)
print(a)
print(a1)
print(a2)
print(a3)

tensor([[0.1250, 0.5869, 0.5045, 0.8987, 0.8551, 0.3928, 0.9676, 0.6524, 0.1898,
         0.9893],
        [0.0295, 0.4268, 0.0102, 0.1591, 0.5835, 0.6335, 0.5721, 0.3427, 0.2330,
         0.4617],
        [0.8992, 0.7195, 0.1406, 0.8332, 0.4989, 0.6686, 0.1325, 0.9412, 0.4899,
         0.8239],
        [0.7685, 0.0921, 0.3204, 0.9481, 0.4835, 0.1664, 0.1954, 0.4896, 0.8400,
         0.1820],
        [0.6034, 0.8791, 0.3861, 0.7537, 0.5626, 0.7481, 0.4266, 0.0125, 0.6743,
         0.6083],
        [0.9078, 0.0796, 0.0481, 0.6453, 0.1891, 0.7718, 0.8126, 0.5951, 0.8554,
         0.3873],
        [0.5473, 0.6716, 0.9901, 0.3919, 0.4433, 0.0503, 0.0464, 0.9867, 0.0226,
         0.0099],
        [0.7377, 0.8883, 0.5586, 0.1437, 0.8726, 0.2016, 0.0847, 0.7568, 0.6720,
         0.1259],
        [0.0960, 0.2300, 0.9126, 0.0803, 0.4656, 0.7938, 0.1763, 0.6281, 0.8881,
         0.7868],
        [0.9870, 0.0558, 0.2993, 0.7850, 0.5864, 0.0010, 0.1038, 0.3170, 0.6433,
         0.2316]])
torch.ret

In [32]:
#方差
a = torch.rand(3,3)
a1 = torch.var(a)
a4 = torch.std(a)#标准差
a2 = torch.var(a,dim = 1,keepdim = True)
a3 = torch.var(a,dim = 0,keepdim = True)
print(a)
print(a1)
print(a4)
print(a2)
print(a3)

tensor([[0.9867, 0.7957, 0.8740],
        [0.0795, 0.4092, 0.7500],
        [0.6472, 0.1135, 0.4446]])
tensor(0.1057)
tensor(0.3252)
tensor([[0.0092],
        [0.1124],
        [0.0726]])
tensor([[0.2101, 0.1170, 0.0488]])


In [35]:
#------------------矩阵运算-----------------------
import torch
a = torch.rand(3,4)
b = torch.rand(1,4)
print(a)
print(b)
#四则运算
print(a+b)
print(torch.add(a,b))#torch.add加法函数
print(b.add(a))
#---------------------------------------
print(a-b)
print(torch.sub(a,b))#减法
print(a.sub(b))
#---------------------------------------
print(a*b)
print(torch.mul(a,b))#乘法
print(a.mul(b))
#---------------------------------------
print(a/b)
print(torch.div(a,b))#除法
print(a.div(b))

tensor([[0.4996, 0.8052, 0.0389, 0.8163],
        [0.7147, 0.0010, 0.9159, 0.0974],
        [0.6824, 0.8870, 0.5038, 0.5798]])
tensor([[0.0922, 0.7313, 0.7137, 0.2561]])
tensor([[0.5917, 1.5365, 0.7526, 1.0724],
        [0.8068, 0.7322, 1.6296, 0.3535],
        [0.7746, 1.6183, 1.2176, 0.8359]])
tensor([[0.5917, 1.5365, 0.7526, 1.0724],
        [0.8068, 0.7322, 1.6296, 0.3535],
        [0.7746, 1.6183, 1.2176, 0.8359]])
tensor([[0.5917, 1.5365, 0.7526, 1.0724],
        [0.8068, 0.7322, 1.6296, 0.3535],
        [0.7746, 1.6183, 1.2176, 0.8359]])
tensor([[ 0.4074,  0.0739, -0.6749,  0.5602],
        [ 0.6225, -0.7303,  0.2022, -0.1587],
        [ 0.5903,  0.1558, -0.2099,  0.3237]])
tensor([[ 0.4074,  0.0739, -0.6749,  0.5602],
        [ 0.6225, -0.7303,  0.2022, -0.1587],
        [ 0.5903,  0.1558, -0.2099,  0.3237]])
tensor([[ 0.4074,  0.0739, -0.6749,  0.5602],
        [ 0.6225, -0.7303,  0.2022, -0.1587],
        [ 0.5903,  0.1558, -0.2099,  0.3237]])
tensor([[0.0460, 0.5888, 0.0277,

In [37]:
#矩阵的平方根
import torch
a = torch.rand(4,4)
print(a.sqrt())
print(a.rsqrt())#平方根的倒数

tensor([[0.9309, 0.3685, 0.4900, 0.7922],
        [0.6131, 0.5386, 0.9820, 0.3026],
        [0.9763, 0.6562, 0.5117, 0.8219],
        [0.5077, 0.6758, 0.8220, 0.8233]])
tensor([[1.0742, 2.7136, 2.0409, 1.2624],
        [1.6311, 1.8568, 1.0184, 3.3044],
        [1.0243, 1.5240, 1.9544, 1.2167],
        [1.9697, 1.4798, 1.2166, 1.2146]])


In [38]:
#矩阵的对数
import torch
a = torch.rand(4,4)
print(a)
print(torch.log2(a))
print(torch.log10(a))

tensor([[0.4619, 0.7144, 0.0625, 0.5620],
        [0.7420, 0.5616, 0.1651, 0.6337],
        [0.5744, 0.2662, 0.0321, 0.5167],
        [0.9296, 0.7954, 0.2457, 0.5150]])
tensor([[-1.1144, -0.4852, -4.0008, -0.8314],
        [-0.4304, -0.8325, -2.5989, -0.6580],
        [-0.7998, -1.9096, -4.9635, -0.9526],
        [-0.1053, -0.3303, -2.0251, -0.9575]])
tensor([[-0.3355, -0.1460, -1.2043, -0.2503],
        [-0.1296, -0.2506, -0.7823, -0.1981],
        [-0.2408, -0.5748, -1.4942, -0.2868],
        [-0.0317, -0.0994, -0.6096, -0.2882]])


In [43]:
#其他函数
a = torch.tensor(3.1415926)
print(a)
print(a.floor())#向上取整
print(a.ceil())#向下取整
print(a.round())#四舍五入
print(a.trunc())#取整数部分
print(a.frac())#取小数部分 默认四位

tensor(3.1416)
tensor(3.)
tensor(4.)
tensor(3.)
tensor(3.)
tensor(0.1416)
